apiVersion: v1
kind: Service
metadata:
  name: sctp-lb1
spec:
  #externalTrafficPolicy: Local
  #loadBalancerClass: loxilb.io/loxilb
  selector:
    what: sctp-test
  ports:
    - port: 9999
      protocol: SCTP
      nodePort: 30010
  type: NodePort 
---
apiVersion: v1
kind: Pod
metadata:
  name: sctp-test
  labels:
    what: sctp-test
spec:
  containers:
    - name: sctp-test
      image: loxilbio/sctp-darn:latest
      imagePullPolicy: Always
      #command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 6 ; done"]
      command: ["sctp_darn","-H", "0.0.0.0","-P", "9999", "-l"]
      ports:
        - containerPort: 9999
