apiVersion: v1
kind: Service
metadata:
  name: tcp-lb-default
  annotations:
    loxilb.io/liveness: "yes"
    loxilb.io/lbmode: "default"
spec:
  externalTrafficPolicy: Local
  loadBalancerClass: loxilb.io/loxilb
  selector:
    what: tcp-default-test
  ports:
    - port: 55002
      targetPort: 80 
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  name: tcp-default-test
  labels:
    what: tcp-default-test
spec:
  containers:
    - name: tcp-default-test
      image: ghcr.io/loxilb-io/nginx:stable
      ports:
        - containerPort: 80
