apiVersion: v1
kind: Service
metadata:
  name: sctp-lb2
  annotations:
    loxilb.io/lbmode: "fullnat"
    loxilb.io/liveness: "yes"
    loxilb.io/secondaryIPs: "134.134.134.1,135.135.135.1"
spec:
  externalTrafficPolicy: Local
  loadBalancerClass: loxilb.io/loxilb
  selector:
    what: sctp-test2
  ports:
    - port: 55004
      protocol: SCTP
      targetPort: 9999
  type: LoadBalancer
  externalIPs: 
    - 133.133.133.1
    - 133.133.133.2
---
apiVersion: v1
kind: Pod
metadata:
  name: sctp-test2
  labels:
    what: sctp-test2
spec:
  tolerations:
  - key: "node.kubernetes.io/disk-pressure"
    operator: "Exists"
    effect: "NoSchedule"
  containers:
    - name: sctp-test2
      image: loxilbio/sctp-darn:latest
      imagePullPolicy: Always
      #command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 6 ; done"]
      command: ["sctp_darn","-H", "0.0.0.0","-P", "9999", "-l"]
      ports:
        - containerPort: 9999
