name: K3s-Flannel-InCluster-L2-Sanity-CI
on:
 schedule:
 # Runs "At 17:00 UTC every day-of-week"
 - cron: '0 17 * * *'
 workflow_dispatch:
    inputs:
      testName:
        description: 'Test Run-Name'     
        required: true
        default: 'k3s-flannel-incluster-l2'
jobs:
  build:
    name: k3s-flannel-incluster-l2-sanity
    runs-on: [self-hosted, large]
    if: github.repository == 'loxilb-io/loxilb' 
          &&  github.event.inputs.tagName == ''
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Run the test
        run: |
         cd cicd/k3s-flannel-incluster-l2
         ./config.sh
         sleep 90
         ./validation.sh
         cd -
         
      - name: Clean test-bed
        if: success() || failure()
        run: |
          cd cicd/k3s-flannel-incluster-l2 || true
          ./rmconfig.sh
          cd -
