name: K3s-Flannel-Cluster-Sanity-CI
on:
 # schedule:
 # Runs "At 11:00 UTC every day-of-week"
 # - cron: '0 11 * * *'
 workflow_dispatch:
    inputs:
      testName:
        description: 'Test Run-Name'     
        required: true
        default: 'k3s-flannel-cluster'
jobs:
  build:
    name: k3s-flannel-cluster-sanity
    runs-on: [self-hosted, large]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: |
         cd cicd/k3s-flannel-cluster
         ./config.sh
         ./validation.sh
         ./rmconfig.sh
         cd -
