name: K8s-Calico-Cluster-IPVS2-Sanity-CI
on:
 schedule:
 # Runs "At 15:00 UTC every day-of-week"
 - cron: '0 15 * * *'
 workflow_dispatch:
    inputs:
      testName:
        description: 'Test Run-Name'     
        required: true
        default: 'k8s-calico-cluster-ipvs2'
jobs:
  test-runner:
    name: k8s-calico-cluster-ipvs2-sanity
    runs-on: [self-hosted, large]
    if: github.repository == 'loxilb-io/loxilb' 
          &&  github.event.inputs.tagName == ''
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          submodules: recursive

    - name: Run the test
      run: |
         cd cicd/k8s-calico-ipvs2
         ./config.sh
         ./validation.sh
         cd -
         
    - name: Clean test-bed
      if: success() || failure()
      run: |
        cd cicd/k8s-calico-ipvs2 || true
        ./rmconfig.sh
        cd -
