name: Liveness-LB-Sanity-CI-RH9

on:
  #schedule:
  # Runs "At 20:00 UTC every day-of-week"
  #- cron: '0 20 * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Liveness LB Sanity Ubuntu 22'
       
jobs:
  build:
    name: liveness-lb-sanity-rh9
    runs-on: [self-hosted, redhat]
    if: github.repository == 'loxilb-io/loxilb'
          &&  github.event.inputs.tagName == ''
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: |
             cd cicd/tcplbmon/
             ./config.sh
             ./validation.sh
             ./rmconfig.sh
             cd -
      - run: |
             cd cicd/udplbmon/
             ./config.sh
             ./validation.sh
             ./rmconfig.sh
             cd -
      - run: |
             cd cicd/sctplbmon/
             ./config.sh
             ./validation.sh
             ./rmconfig.sh
             cd -
      - run: |
             cd cicd/tcplbmon6/
             ./config.sh
             ./validation.sh
             ./rmconfig.sh
             cd -
      - run: |
             cd cicd/tcplbepmod/
             ./config.sh
             ./validation.sh
             ./rmconfig.sh
             cd -
      - run: |
             cd cicd/httpsep/
             ./config.sh
             ./validation.sh
             ./rmconfig.sh
             cd -
      - run: |
             cd cicd/http2ep/
             ./config.sh
             ./validation.sh
             ./rmconfig.sh
             cd -
      - name: Clean test-bed
        if: success() || failure()
        run: |
            sudo ip -all netns delete
            dps=$(sudo docker ps -a -q)
            if [[ x$dps != x ]]; then
              sudo docker stop $(sudo docker ps -a -q)
              sudo docker rm $(sudo docker ps -a -q)
            fi
            sudo docker image rm ghcr.io/loxilb-io/loxilb:latest
