apiVersion: v1
kind: Pod
metadata:
  name: pod-01
  labels:
    app: pod-01
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan1
spec:
  containers:
    - name: nginx
      image: ghcr.io/loxilb-io/nginx:stable
      ports:
        - containerPort: 80
