apiVersion: v1
kind: Service
metadata:
  name: sctp-lb2
  annotations:
   loxilb.io/liveness: "yes"
   loxilb.io/lbmode: "default"
spec:
  loadBalancerClass: loxilb.io/loxilb
  #externalTrafficPolicy: Local
  selector:
    what: sctp-test2
  ports:
    - port: 55005
      protocol: SCTP
      targetPort: 10001
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  name: sctp-test2
  labels:
    what: sctp-test2
spec:
  containers:
    - name: sctp-test2
      image: alpine/socat
      command: [ "sh", "-c"]
      args:
      - while true; do
          socat -v -T2 sctp-l:10001,reuseaddr,fork system:"echo 'server1'; cat";
          sleep 20;
        done;
      ports:
        - containerPort: 10001
      env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
