apiVersion: v1
kind: Service
metadata:
  name: udp-lb2
  annotations:
   loxilb.io/liveness: "yes"
   loxilb.io/lbmode: "fullnat"
spec:
  loadBalancerClass: loxilb.io/loxilb
  selector:
    what: udp-test2
  ports:
    - port: 55006
      protocol: UDP
      targetPort: 33333
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  name: udp-test2
  labels:
    what: udp-test2
spec:
  containers:
    - name: udp-test2
      image: loxilbio/udp-echo
      ports:
        - containerPort: 33333
