apiVersion: v1
kind: Service
metadata:
  name: sctp-lb-default
  annotations:
   loxilb.io/lbmode: "onearm"
spec:
  loadBalancerClass: loxilb.io/loxilb
  externalTrafficPolicy: Local
  selector:
    what: sctp-default-test
  ports:
    - port: 57004
      protocol: SCTP
      targetPort: 9999
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  name: sctp-default-test
  labels:
    what: sctp-default-test
spec:
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: Exists
    - key: "node-role.kubernetes.io/control-plane"
      operator: Exists
  affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: "node-role.kubernetes.io/master"
              operator: Exists
            - key: "node-role.kubernetes.io/control-plane"
              operator: Exists
  containers:
    - name: sctp-default-test
      image: ghcr.io/loxilb-io/alpine-socat:latest
      command: [ "sh", "-c"]
      args:
      - while true; do
          socat -v -T2 sctp-l:9999,reuseaddr,fork system:"echo 'server1'; cat";
          sleep 20;
        done;
      ports:
        - containerPort: 9999
      env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
