apiVersion: v1
kind: Service
metadata:
  name: dummy
  annotations:
      loxilb.io/staticIP : "4.0.6.100"
spec:
 loadBalancerClass: loxilb.io/loxilb
 type: LoadBalancer 
 ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: dummy
subsets:
  - addresses:
    - ip: 4.0.5.3
    ports:
    - port: 80
