name: Deploy to GitHub Pages

on:
  push:
    branches:
      - dev  # 배포할 브랜치를 지정

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy index.html to root
        run: cp templates/index.html ./index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # 현재 디렉토리를 배포 디렉토리로 지정
